### ISSUE TITLE
[Question] About CommandSequence exception handling

### ISSUE THREAD

**Issue by xaviersolau** [lucabriguglia/Kledex#100]
I am wandering what append if an error occurs in one of the command while processing a CommandSequence ?

I did run some tests on my side and I noticed that I have part of the events stored in my db even if my command sequence is not fully executed. Is this behavior expected ?
Since the sequence is not successful, shouldn't we prevent events to be stored ?

**Comment by lucabriguglia** [comment]
We should and the way I'd like to handle it is by using an ambient transaction but unfortunately this can't be done at the moment because distributed transactions are not currently supported in .NET Core.

**Comment by lucabriguglia** [comment]
In the mean time we could implement a mechanism to trigger compensation steps in case of errors. In order to achieve this we should also add more functionalities to the store providers such as deleting rows which are not currently supported.

**Comment by lucabriguglia** [comment]
Refer to #101
