### ISSUE TITLE
Kledex 2.5.1 - Event handlers get called twice

### ISSUE THREAD

**Issue by quentin-villevieille** [lucabriguglia/Kledex#110]
Hi,
I'm using Kledex 2.5.1 with a .net core 3.1 app. I use the event sourcing & cqrs features.

Everything is working fine except one thing : **the event handlers are called twice**. 
So far, I had only one event handler, so I thought I would create another event handler to check whether the behaviour was the same or not. Both event handlers are called twice - they are called at the same time.

Have you experienced this bug before ? Or am I missing something here ?

Thanks !

**Comment by quentin-villevieille** [comment]
Drop it, it was in the `Startup.cs` inside the AddKledex config method.
And someone already had this 'issue'... so, my bad !

**Comment by lucabriguglia** [comment]
No problem :-)
