### ISSUE TITLE
Decorate an event handler

### ISSUE THREAD

**Issue by quentin-villevieille** [lucabriguglia/Kledex#112]
Hi guys,

I'm trying to decorate a class that implements `IEventHandlerAsync<T>`. 
I'm using AutoFac as my DI framework.
As far as I understand, Kledex registers all the classes that implements this interface `IEventHandlerAsync` even the decorator, so it ends up creating a circular reference...

Any idea ? 

Thanks !

**Comment by lucabriguglia** [comment]
HI @quentin-villevieille, yes all implementations are registered automatically if you pass the types when registering the library:
```
services.AddKledex(typeof(Product));
```
where `Product` is a type in the library that you want to auto register all the implementations from.
You can try to register Kledex without passing any types:
```
services.AddKledex();
```
and then register your implementations manually:
```
services.AddKledex();
services.AddTransient(typeof(IEventHandlerAsync<CreateProduct>), typeof(CreateProductHandler));
```

**Comment by quentin-villevieille** [comment]
cool, I'll try that, thanks!

**Comment by lucabriguglia** [comment]
Also, remember that for your commands you can pass your own method without the need of implementing a ICommandHandlerAsync<T> interface. More info [here](https://lucabriguglia.github.io/Kledex/Commands).
