### ISSUE TITLE
[Question] What is the process to contribute?

### ISSUE THREAD

**Issue by xaviersolau** [lucabriguglia/Kledex#114]
Hello,

I am planning to add support for .Net 5 in my projects some time soon and I am considering to make a PR to your project with the .Net5 support.
Do you have recommendation about the way or the process to contribute to your project?

Regards,

**Comment by xaviersolau** [comment]
Do you have any plane about adding new features to Kledex?

**Comment by lucabriguglia** [comment]
Hi!

First of all, yes I'm planning to add more features to Kledex and I'm going to start from January.
This year I've been very busy with work and Master's Degree but I'm going to submit my dissertation by the end of the year!

Your question reminded me that I need to add a proper contribution guidelines, thanks for that.

First thing I'll do with the new year is to migrate to .NET5 and update the version to 3.0.

**Comment by xaviersolau** [comment]
Ok thanks for that!

I'am looking forward! 👍
