### ISSUE TITLE
Connection strings should be under Connection Strings object

### ISSUE THREAD

**Issue by asokalskyy** [lucabriguglia/Kledex#34]
Now it's look like 

_"ServiceBusConfiguration": {
    "ConnectionString": "Endpoint=sb://"
  },
  "DomainDbConfiguration": {
    "ConnectionString": "Data Source=.\\;"
  },
  "ConnectionStrings": {
    "SqlConnection": "Data Source=.\\"
  },_

For applications published on Azure connection strings are hidden, so better to put them under correct object. 

_"ConnectionStrings": {
    "SqlConnection": "Data Source=.\\",
    "DomainDbConfiguration": Data Source=.\\;",
    "ServiceBusConfiguration": "Endpoint=sb://"
  },_

**Comment by andreujuanc** [comment]
I just had this thought a few days ago when I deployed a prototype into azure app service.
+1

**Comment by lucabriguglia** [comment]
Good observation.

**Comment by lucabriguglia** [comment]
I'm adding all connection strings under "ConnectionStrings":
- KledexDomainStore
- KledexMessageBus
- KledexRedisCache

The only exception will be CosmosSql as it needs to inputs: ServiceEndpoint and AuthKey.
For that I'm adding the new section KledexCosmosSqlConfiguration.

Another change is for the remaining options (database name, collection name, etc.), I'm adding the options as override when register the services.

**Comment by lucabriguglia** [comment]
Released in version 2.2.0
