### ISSUE TITLE
Run commands/queries  in background

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [lucabriguglia/Kledex#46]
I did make hangfire (fire and forget job), but nothing happened. For command/events execution needs context ?

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
at OpenCqrs.Dependencies.Resolver.ResolveT
at OpenCqrs.Dependencies.HandlerResolver.ResolveHandlerTHandler
at OpenCqrs.Queries.QueryProcessor.ProcessAsync[TQuery,TResult](TQuery query)

**Comment by lucabriguglia** [comment]
Sorry for the delay, do you have a repo I can see?

**Comment by Ilchuk-Mihail** [comment]
No, I can't show repo. It's private repo. 
But I can create demo for you (with hangfire) if needed.

**Comment by lucabriguglia** [comment]
It would be good, I need a way to replicate it.

**Comment by Ilchuk-Mihail** [comment]
@lucabriguglia I will prepare some example for you .

**Comment by lucabriguglia** [comment]
Hi guys I'm closing this issue as there's not been any activity for a while.
