### ISSUE TITLE
Add event version and event upgrade support

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [lucabriguglia/Kledex#47]

**Comment by lucabriguglia** [comment]
Can you describe in details what you would like to achieve?

**Comment by Ilchuk-Mihail** [comment]
It is more depend on event sourcing.

For example: 
For a long time we had domain model with some Data, and has a bunch of events in event store. 
Now we need to update our domain model, and need some mechanism to apply old events. 
Because now we have new domain model and new events. 

So, I propose to have some Event Version as a metadata. When our app produce new events, their would be in different  version. That way we can have different applies methods for different event versions, and support old and new events. 

Or we need some mechanism to upgrade old events to new domain representation.   

Any thoughts about that case?

**Comment by lucabriguglia** [comment]
Events should be immutable, your domain should be responsible to apply old and new events.

**Comment by Ilchuk-Mihail** [comment]
@lucabriguglia  yes events immutable "in ideal world :) )"

Just worry if it will not be a problem in future. 

> your domain should be responsible to apply old and new events.

Is it not a problem to continue support this logic ? 


Check this : 

Versioning of Events in Event Sourced Systems
https://www.infoq.com/news/2017/07/versioning-event-sourcing

And some solutions to Problem: Evolving events
https://ookami86.github.io/event-sourcing-in-practice/#slide-51

**Comment by lucabriguglia** [comment]
I agree with what Young says and I believe that events should not be modified as it would cause a lot of problems.

**Comment by lucabriguglia** [comment]
Closing as it has not been active for a while.
