### ISSUE TITLE
Set Aggregate in Command (simplify dispatcher)

### ISSUE THREAD

**Issue by lucabriguglia** [lucabriguglia/Kledex#51]
Add IDomainCommand<IAggegate> as suggested by @andreujuanc

**Comment by andreujuanc** [comment]
Is this for v7? :)

**Comment by lucabriguglia** [comment]
Well, it may be. I'm playing around a little bit and it looks like it would need a lot of refactoring at every level.

**Comment by lucabriguglia** [comment]
And also, I don't see a way of achieving it without using reflection and therefore having repercussions on performance.

**Comment by lucabriguglia** [comment]
Merged to branch release/2.0
