### ISSUE TITLE
Custom properties in bus message

### ISSUE THREAD

**Issue by lucabriguglia** [lucabriguglia/Kledex#55]

**Comment by andreujuanc** [comment]
I would love to discuss how we'll implement this custom properties for Rabbit, since the rabbit message it's just a byte[], how would we approach it? Should we place some kind of contract based on a specification? Or maybe some OpenCQRS properties.

**Comment by lucabriguglia** [comment]
Good question, I don't know yet. Please feel free to comment with any ideas and we'll discuss them.

**Comment by lucabriguglia** [comment]
@andreujuanc are you creating a new pull request for this issue? If not, I can create a new branch and work on it ;-)

**Comment by andreujuanc** [comment]
I am, but I was out on holidays. I will post code today :)

**Comment by andreujuanc** [comment]
So, @lucabriguglia , are you not happy with the last PR I submitted? #54 

I think that https://github.com/andreujuanc/OpenCQRS/blob/a20db7c101e34c2be56689a63a8ac7ae03c7178c/src/OpenCqrs.Bus.ServiceBus/Factories/MessageFactory.cs#L22 is enough for this requirement.

I just added custom properties for rabbit:
https://github.com/andreujuanc/OpenCQRS/blob/35d3bec2e13c0728c38b58e1ba258dbcb1347fd4/src/OpenCqrs.Bus.RabbitMQ/Factories/MessageFactory.cs#L20
https://github.com/andreujuanc/OpenCQRS/blob/35d3bec2e13c0728c38b58e1ba258dbcb1347fd4/src/OpenCqrs.Bus.RabbitMQ/Topics/TopicClient.cs#L39

What do you think?  Havent done the tests for it, yet.

**Comment by lucabriguglia** [comment]
It was just because the project renaming obviously changed the structure.

**Comment by andreujuanc** [comment]
I messed my repo, gonna clean it and submit the PR after. Time to pick some 🍒  D:

**Comment by lucabriguglia** [comment]
Okay, no problem :-)

**Comment by andreujuanc** [comment]
https://github.com/lucabriguglia/Kledex/pull/59
What do you think?

**Comment by lucabriguglia** [comment]
sorry for the delay, I'll have a look today :-)

**Comment by lucabriguglia** [comment]
Pull request merged
