### ISSUE TITLE
Renaming the project

### ISSUE THREAD

**Issue by lucabriguglia** [lucabriguglia/Kledex#57]
I'm thinking about a new name for the project. The main reason is that the framework can be useful even in projects that don't use CQRS or Event Sourcing. It can be used just to create a simple and clean design enforcing single responsibility and separation of concerns. It should not be coupled just to the CQRS concept.

**Comment by andreujuanc** [comment]
I must agree, tho I found the project because of the naming :)

~~OpenCQRSWithEventSourcingAndDDD Is a bit of a tongue twister~~

Yesterday I was explaining SOLID principles to a friend and maybe we can use that as a base to create the name? For example OpenSOLID, Solidfy,  Or in other languages like OpenKotai or just Kotai in japanese sounds good, tho, katai (hard) rolls easier.

Naming is the hardest kind of issues C:

**Comment by lucabriguglia** [comment]
Oh definitively, naming is everything :-)

**Comment by lucabriguglia** [comment]
I like the term Kotai

**Comment by lucabriguglia** [comment]
I might have found the new name, looking for the available domain names ;-)

**Comment by andreujuanc** [comment]
Nice! can't wait 🎆 
I recommend cloudflare.com as a registrar 👀

**Comment by lucabriguglia** [comment]
Thanks but I have all my domain names with the same registrar, the same for the last 20 years I believe :-)

**Comment by lucabriguglia** [comment]
I'm still undecided, I like your suggestion for japanese names tough

**Comment by lucabriguglia** [comment]
Okay, name chosen. With the new name versions will start from 1.0.
More to come.

**Comment by andreujuanc** [comment]
** INSERT DRUM ROLL **

**Comment by lucabriguglia** [comment]
The new name is **Kledex**  and version 1.0.0 has already been published to NuGet.

**Comment by andreujuanc** [comment]
Sounds techie. C:

**Comment by lucabriguglia** [comment]
This was the process :-)
Clean Design > Cle Des > Cledes > Kledes > Kledex

**Comment by andreujuanc** [comment]
Great! At first i was like UHM, sounds like Kleenex, then I was like, oh, that's actually good!
Btw, besides all the goodies, Klendex also helps with mediator pattern. ** read me **  ** wink wink **

**Comment by lucabriguglia** [comment]
Kledex not Klendex 😂
