### ISSUE TITLE
Stores' access modifier

### ISSUE THREAD

**Issue by andreujuanc** [lucabriguglia/Kledex#58]
Small example, for AggregateStore in Cosmos.Sql is internal but Cosmos.Mongo is public.

I see no harm in exposing them as public. Should they be all public?
For now the only way to use the Cosmos.Sql AggregateStore is via DI and aspnet builder.

What you guys think?

UPDATE:
This should also apply to some base classes and most interfaces.

**Comment by lucabriguglia** [comment]
I'll have a look, it is inconsistent anyway which is not good.
