### ISSUE TITLE
AutoMapper configuration

### ISSUE THREAD

**Issue by andreujuanc** [lucabriguglia/Kledex#60]
AFAIK, there is no way to modify AM configuration.  So, I think we should use profiles or some similar mechanisms to allow the user to further configure automapper, since we adding it we might as well let other people configure it. 

What you guys think about this?

**Comment by lucabriguglia** [comment]
It's okay in principle, but what do the users would customize? AutoMapper at the moment is just used for a one to one internal mapping.

**Comment by andreujuanc** [comment]
If I want to use Automapper for my own stuff, I would have to have a separate instance and IMapper cannot be used because Kledex already added to the services. 
There is some mapping I wanted to customize and I coudn't.
Anyway I leave this here anyway as a reminder, since for that project we'll be using https://github.com/MapsterMapper/Mapster instead,

**Comment by lucabriguglia** [comment]
I think you can use AutoMapper with no issues. You should be able to register your own mapper configuration.

**Comment by lucabriguglia** [comment]
Hi @andreujuanc  I'm closing this issue as there's not been any activity for a while.
