### ISSUE TITLE
AggregateRoot does not increment version when applying events

### ISSUE THREAD

**Issue by hellfirehd** [lucabriguglia/Kledex#62]
```csharp
[Test]
public void Create()
{
  var aggregate = new Aggregate();
  Assert.AreEqual(1, aggregate.Events.Count);
  Assert.AreEqual(1, aggregate.Version);
}
```

**Comment by lucabriguglia** [comment]
Let me check and I'll get back to you.

**Comment by hellfirehd** [comment]
Here's a better test suite:

https://gist.github.com/hellfirehd/35438749aa31366d4ebfbd997db286ff

**Comment by andreujuanc** [comment]
I think you need to save the aggregate in order to get the version increment. I can be totally wrong, lets wait for Luca to give the final answer.

**Comment by lucabriguglia** [comment]
Got it, version is currently updated only when the aggregate is loaded from history which means that the aggregate needs to be saved first. This was the intendent behaviour and now I'm wondering if it was the right decision. What do you guys think?

**Comment by andreujuanc** [comment]
It makes sense to change the version if it actually saved, and also after all things have been done to it, but then, Version = Event.Count all the time, right?

So we can actually have more info if we get the version to work as @hellfirehd 's gist intended, which is to increment the version number one time per "Apply".

Very interesting indeed.

**Comment by hellfirehd** [comment]
I think if an event is applied, the version should update.  For example, if I'm stepping through the events for auditing purposes I want to see what the version of the AggregateRoot is after each event is applied.  

The following fix passes all tests including the ones I provided:

```csharp
public void LoadsFromHistory(IEnumerable<IDomainEvent> events)
{
  var domainEvents = events as IDomainEvent[] ?? events.ToArray();

  foreach (var @event in domainEvents)
  {
    ApplyEvent(@event);
  }
}


protected void AddAndApplyEvent(IDomainEvent @event)
{
  _events.Add(@event);
  ApplyEvent(@event);
}

private void ApplyEvent(IDomainEvent @event)
{
  this.AsDynamic().Apply(@event);
  Version++;
}
```

Additionally, this is also important for checking concurrency violations and out of order event violations in distributed systems.  For example:

```csharp
private void ApplyEvent(IDomainEvent @event)
{
  if (@event.Version == 0)
  {
    throw new ApplicationException($"{evnt.GetType()} version {@event.Version} must not be 0.");
  }

  if (@event.Version != Version + 1)
  {
    throw new ApplicationException($"{@event.GetType()} version {@event.Version} cannot be applied to version {Version}.");
  }

  this.AsDynamic().Apply(@event);
  Version++;
}
```
However, that would be a breaking change as it requires adding Version to IDomainEvent.

**Comment by lucabriguglia** [comment]
I get your point and I agree on increasing the version when applying events. On the concurrency violation there is already a feature for checking it. You can populate the expected version property in the command.

**Comment by lucabriguglia** [comment]
But I can see the reasons to be there instead
