### ISSUE TITLE
Business rules and validation

### ISSUE THREAD

**Issue by agolaszewski** [lucabriguglia/Kledex#64]
I was exploring/debugging GettingStarted and one think struck me.
Lets say that i have a business rule that states : product title must be unique.
Now lets image that I have command in a bus with title : "Test"
Now I add another product with name "Test" to the queue. It would require to scan entire commands queue to check if there is another command with same title.
Things get even more complicated as we put event (ProductCreated) in its own queue
Now I also have to scan it somehow.
How to overcome this problem?

**Comment by lucabriguglia** [comment]
You should put your validation in the command handler. You need a rule to check if a product with name "Test" already exists. If your are using event sourcing you should check your read model. If you are not using event sourcing, just check in the db.

**Comment by lucabriguglia** [comment]
Hi @agolaszewski I'm closing this issue as there's not been any activity for a while.
