### ISSUE TITLE
Should I use IDomainCommandHandlerAsync or ICommandHandlerAsync?

### ISSUE THREAD

**Issue by rulrok** [lucabriguglia/Kledex#71]
Hello,

on the wiki page it presents us the an example where the command handler inherits from `ICommandHandlerAsync`.

But on code, in `examples > Commands > Handlers`, the examples inherit from `IDomainCommandHandlerAsync`.

What would be the difference?

**Comment by lucabriguglia** [comment]
Use `ICommandHandlerAsync` for simple commands that don't need any domain functionality like store domain events.
Use `IDomainCommandHandlerAsync` when working on your domain and want to save the domain events to an event store.

**Comment by lucabriguglia** [comment]
No problem :-)

**Comment by lucabriguglia** [comment]
In version 2.0 I'm removing the IDomainCommandHandler andIDomainCommandHandlerAsync interfaces. The only interfaces to be used will be ICommandHandler and ICommandHandlerAsync. I'm also simplifying the dispatcher and merging the two command senders.

**Comment by rulrok** [comment]
That's a good move.

I've noticed that today because of the different overloads of methods on the dispatcher, I need to explicitly inform the generic types, and it is easy to misinform one of them and the dispatcher won't find the handler, even if there's only one handler.
