### ISSUE TITLE
Will the .Net Core 3.0 version be updated? 

### ISSUE THREAD

**Issue by bakbuz** [lucabriguglia/Kledex#73]
Will the new version be updated?

**Comment by lucabriguglia** [comment]
Yes, version 1.2 will be on 3.0.

**Comment by bakbuz** [comment]
Thank you!

**Comment by rulrok** [comment]
But will it keep also targeting `.netstandard2.0`?

**Comment by lucabriguglia** [comment]
It's already targeting .netstandard2.0, it will target .netstandard2.1

**Comment by rulrok** [comment]
I mean, will you drop support for `.netstandard2.0`?
I hope not as I have a `.net 4.7.2` project and it is limited to `.netstandard2.0` upmost.
I wouldn't be able to receive updates if only targeting `.netstandard2.1`.

**Comment by lucabriguglia** [comment]
Oh okay, don't worry it will still work :-)

**Comment by rulrok** [comment]
@lucabriguglia I'm trying to update to version `1.2.0`, but the nuget doesn't target `.netstandard2.0`, only `.netstandard2.1`.

**Comment by lucabriguglia** [comment]
Yes sorry I was wrong with my previous comment, let me what I can do.

**Comment by lucabriguglia** [comment]
@rulrok I have just released a special version (1.3.0) which is basically the same as 2.1.0 functionality wise but targeting netstandard2.0.
Please let me know if it works in your app!
