### ISSUE TITLE
Is outbox pattern viable?

### ISSUE THREAD

**Issue by rulrok** [lucabriguglia/Kledex#74]
If I understand, outbox could be a mechanism for messaging queue but without relying on external services like message bus; it could just work on the same sql server used for aggregates.

It would require querying database like every 15 seconds or something to consume messages.

Any thoughts if that fits the project?

**Comment by lucabriguglia** [comment]
It does fit the project but it's not implemented by default. You need to create a service that queries the data store whatever it is and processes the messages. Obviously you need an extra data store or something to track the messages as picked up and processed.

**Comment by lucabriguglia** [comment]
Closing as it has not been active for a while.
