### ISSUE TITLE
How to communicate between multiple domains?

### ISSUE THREAD

**Issue by rulrok** [lucabriguglia/Kledex#76]
I'm trying to make every domain I have into a separate class library project.
So far I have only one for `billing`, but I know I will have in the future other domains which must respond to events from `billing` domain.

Example:
Someone renews their subscription and the `billing` domain emits a `subscriptionRenewedEvent`.
In another domain, say, `staffManagement`, I will need to handle the event.

So far that indicates that I should have the following projects:
`Domain.Billing`
`Domain.Billing.Events`
`Domain.StaffManagement`

So I can have the references:
`Domain.Billing` -> `Domain.Billing.Events` <- `Domain.StaffManagement`

The main problem I anticipate is to have kinda of circular references.
Say domain A emits events that domain B handles, and vice-versa.

I think that by creating a separate `Events` project for each domain project solves the issue, but I'd like to hear suggestions if you know something better.

**Comment by lucabriguglia** [comment]
Creating separate libraries for the domain events is absolutely fine.
Also, bear in mind that if you work on a microservices architecture, you could use the message bus functionality to comunicate beween them.

**Comment by lucabriguglia** [comment]
Closing as it has not been active for a while.
