### ISSUE TITLE
Is Source field intended for generic logging?

### ISSUE THREAD

**Issue by rulrok** [lucabriguglia/Kledex#78]
Hi

I don't see a particular usage on Kledex code _per se_, so I'm assuming I could use it for putting any information I'd like.

They are located in `IDomainCommand` and `IDomainEvent`.

I'm planning to use that for logging user IP, browser version, etc.

Is that so?

**Comment by lucabriguglia** [comment]
Hi, it was meant to be used for the source of the command and therefore of the events (e.g. api 1, api 2, site 1, site 2, etc...)

**Comment by lucabriguglia** [comment]
Closing as it has not been active for a while.
