### ISSUE TITLE
Any plane for saga

### ISSUE THREAD

**Issue by hasibul2363** [lucabriguglia/Kledex#80]
Thank you very much for sharing such wonderful framework. I just want to know do you have any plane to incorporate saga with Kledex?

**Comment by etiennecl** [comment]
Is this supported with the CommandSequence pattern implemented in version 2.3?

**Comment by lucabriguglia** [comment]
Let's say that the CommandSequence could be considered as the saga manager in a orchestration based saga.

**Comment by lucabriguglia** [comment]
Refer to #101
