### ISSUE TITLE
Issue with MongoDB.Driver library v2.8.0

### ISSUE THREAD

**Issue by quentin-villevieille** [lucabriguglia/Kledex#83]
Hi guys,

There seems to be a bug with MongoDB.Driver v2.8.0. I had the following error message :

`System.TypeInitializationException : 'The type initializer for 'MongoDB.Bson.Serialization.BsonClassMap' threw an exception.'`

I added a reference to MongoDB.Driver v2.9.2 and it works just fine !

Btw, great project!

**Comment by lucabriguglia** [comment]
Thanks @quentin-villevieille! I'll upgrade the reference :-)
