### ISSUE TITLE
Unify command handlers

### ISSUE THREAD

**Issue by lucabriguglia** [lucabriguglia/Kledex#85]

**Comment by lucabriguglia** [comment]
I'm getting rid of `IDomainCommandHandler` interface and all type of commands will use the `ICommandHandler` interface.

**Comment by andreujuanc** [comment]
BRILLIANT. 
I'm no longer working on the project in which we used Kledex. But this is a very welcome change.
More than once we had to debug code that was "not working" and the confusion was mostly on those interfaces/dispatchers.

**Comment by lucabriguglia** [comment]
Changes already in issue-85-command-handlers branch

**Comment by lucabriguglia** [comment]
I have also merged the command senders

**Comment by lucabriguglia** [comment]
Merged to release/2.0 branch
