### ISSUE TITLE
How command handler invoked when we are using RabbitMq as a Bus

### ISSUE THREAD

**Issue by hasibul2363** [lucabriguglia/Kledex#89]
According to documentation, I have added following to send command using Bus
`  .AddRabbitMQProvider()`
`  await _dispatcher.DispatchBusMessageAsync(command);`
I have found it was storing message in rabbit MQ.
My question is what type of configuration I need to do to trigger CommandHandler.
Is there any sample that I can follow.
Expecting your help.
Thanks in advance.

**Comment by lucabriguglia** [comment]
You need to call _dispatch.SendAsync(command) in order to trigger the command handler and then as part of the command response return event(s) that implements eirher the IQueueMessage or ITopicMessage interfaces. When an event implements one of those interfaces is automatically dispatch to the message bus.

**Comment by lucabriguglia** [comment]
I'm planning to create a few diagrams to explain better how the flows work.

**Comment by kwentinn** [comment]
Brilliant idea!

**Comment by hasibul2363** [comment]
@lucabriguglia 
Thank you very much for your response. Yes, you are correct if I use `_dispatch.SendAsync(command)` then handler invoked and that is from in memory (meaning the same project).

If I would like to handle command through the bus then what things I need to do? I have used `IBusQueueMessage` to create message. When I am using `_dispatcher.DispatchBusMessageAsync(command)`; it sends message to bus but handler was not invoked.

Does command handler invoked based on BusMessage or not? Or I need to write my own code to invoke handler by listening message from Bus?

Does Kledex only push message to bus and don't handle it?

Expecting your help.

**Comment by lucabriguglia** [comment]
@hasibul2363 yes you need to write your own code to handle the command (or an event). What Kledex does at the moment is just to put a message on the bus queue or topic (normally an event after the execution of a command handler). But thanks because this is a functionality that might be implemented.

**Comment by lucabriguglia** [comment]
Just published the first diagram in the [README](https://github.com/lucabriguglia/Kledex/blob/master/README.md) file.
