### ISSUE TITLE
How to work with DbContexts

### ISSUE THREAD

**Issue by baoduy** [lucabriguglia/Kledex#91]
Hi, 
How could we implement the multi DbContexts with EfCore? Please share if there is any sample available?

**Comment by lucabriguglia** [comment]
Hi, what do you mean with multi DbContext?

**Comment by baoduy** [comment]
Hi @lucabriguglia 
As you know the DDD has an concept is BoundedContext, to implement with Entity Framework Core. I'm using DbContext as my BoundedContext and within an application we may have more than 1 Bounded Contexts and I would like to check how to link them to Kledex Storage?

**Comment by lucabriguglia** [comment]
Hi @baoduy 
You may use the property "Source" when sending a command. That value is saved with all commands and events and therefore you will be able to "group" data by context (source)

**Comment by baoduy** [comment]
As I saw currently, Kledex is only support a single DbContext. This consider is single BoundedContext Shall I raise a request for to support Multi BoundedContext concept?

**Comment by lucabriguglia** [comment]
Yes @baoduy

**Comment by lucabriguglia** [comment]
Closing this for the time being, a new issue or pull request should be raised.
