### ISSUE TITLE
Mapping commands and events

### ISSUE THREAD

**Issue by quentin-villevieille** [lucabriguglia/Kledex#93]
Hi,
Is mapping commands to events a good idea ? The properties inside a command and an event are often exactly the same, there seems to be a strong link between the two classes.

**Comment by lucabriguglia** [comment]
Hi, 
you are right that they are often the same but potentially a command can produce multiple events.
Also, your business logic might change over time which may result in different values for the events (e.g. object status) and you might want to keep trace of that (same command creating an object with a different status).

**Comment by quentin-villevieille** [comment]
Yeah, I guess that would create too much coupling between commands & events.
