### ISSUE TITLE
Events saved twice in event store

### ISSUE THREAD

**Issue by quentin-villevieille** [lucabriguglia/Kledex#94]
Hi,

I've noticed that sometimes the events get saved twice in the event store, have you ever experienced this bug ?

**Comment by lucabriguglia** [comment]
No, never. Are you able to reproduce it?

**Comment by lucabriguglia** [comment]
What store provider?

**Comment by quentin-villevieille** [comment]
With mongo db store provider. It's weird. It's not always the case though. I'll try to show you an example where it does so

**Comment by lucabriguglia** [comment]
Thanks @quentin-villevieille!

**Comment by lucabriguglia** [comment]
Are aggregates and commands duplicated as well or just events?

**Comment by quentin-villevieille** [comment]
Forget it ! I did something wrong in my code... I thought I needed to call specifically the `_repository.Save(aggregate)` at the end of the command handler, before returning the events, but I don't, right ?

**Comment by lucabriguglia** [comment]
Ah okay! No you don't need to, it's all done by the framework 😁
