### ISSUE TITLE
Application templates

### ISSUE THREAD

**Issue by lucabriguglia** [lucabriguglia/Kledex#96]
Templates for applications that follow the Kledex patterns.

**Comment by lucabriguglia** [comment]
I have decided to create a separate repository instead of having templates inside the Kledex repository: [CQRS Starter Kit](https://github.com/lucabriguglia/CQRS-Starter-Kit).

**Comment by abomadi** [comment]
@lucabriguglia amazing project mate, it really helps  instead of writing it from the scratch, would you show an example for RabbitMQ  inside DDD-CQRS-ES Starter Kit as well?

**Comment by lucabriguglia** [comment]
Thanks @abomadi and yes I can add an example for RabbitMQ. The first version will be very basic but I'm going to add more stuff over time.

**Comment by abomadi** [comment]
@lucabriguglia Amazing, i just wanted to see how rmq is consuming events as i was looking at it's provider but couldn't find any subscribe / consume methods over there

**Comment by lucabriguglia** [comment]
It's pretty standard, this is a tutorial for queues: https://www.rabbitmq.com/tutorials/tutorial-two-dotnet.html

**Comment by lucabriguglia** [comment]
First version of the starter kit released and available [here](https://github.com/lucabriguglia/DDD-CQRS-ES-Starter-Kit).

**Comment by kwentinn** [comment]
Amazing work, mate! 👍👏

**Comment by lucabriguglia** [comment]
Thanks @kwentinn! As always suggestions and feature requests are more than welcome :-)
