### ISSUE TITLE
[Question] Is there any plan to use Microsoft.Azure.Cosmos ?

### ISSUE THREAD

**Issue by xaviersolau** [lucabriguglia/Kledex#97]
Do you plan to add cosmos support with Microsoft.Azure.Cosmos (Azure Cosmos DB version 3) ?

Do you think we could get any benefit from this new API?

**Comment by lucabriguglia** [comment]
Yes, I was planning to update it in one of the next releases.
I think going forward is the natural choice.

**Comment by lucabriguglia** [comment]
Microsoft.Azure.Cosmos will be introduced with the new Entity Framework Cosmos provider (#30).
