### ISSUE TITLE
Kledex adds "everything" to the ServiceCollection twice, or more.

### ISSUE THREAD

**Issue by PiekJ** [lucabriguglia/Kledex#99]
Hello,

I'm currently doing some tests with Kledex. I have a project containing two aggregates and both are added to the `AddKledex` method as followed: 
```
serviceCollection.AddKledex(setupAction, typeof(BankAccountAggregate), typeof(TransactionAggregate));
```
The problem that now occurs is that all the services are added twice, causing undefined and unwanted behavior. For example the event handlers are executed twice, instead of single time.

Personally I'd like to see a way to add all my services manually, instead of everything (even non Kledex interfaces and classes).

**Comment by lucabriguglia** [comment]
Hi @PiekJ, are BankAccountAggregate and TransactionAggregate in the same project?
If they are, it's the reason why everything is registered twice.
You need to pass one type per project and not every aggregate.

**Comment by lucabriguglia** [comment]
Assuming this has been resolved.
